server:
  port: 8080

logging:
  level:
    org.springframework: DEBUG


spring:
  messages:
    basename: messages

  jpa:
    show-sql: true
    #jpa data.sql -> 하이버네이트 테이블 생성 이후에 동작할 수 잇도록 해줌
    defer-datasource-initialization: true

  #h2 inmemory db 설정
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb


#  security:
#    user:
#      name: hyunsoo
#      password: passw0rd

#actuator management 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"





