server:
  port: 8080

logging:
  level:
    org.springframework: DEBUG


spring:
  messages:
    basename: messages


#  security:
#    user:
#      name: hyunsoo
#      password: passw0rd

#actuator management 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"




